
---

  - name: Set listen port to default
    lineinfile:
      dest: "/etc/kibana/kibana.yml"
      regexp: "^#?server.host"
      line: "server.host: \"0.0.0.0\""
    notify: Restart Kibana

  - name: Starting Kibana
    systemd:
      name: kibana
      state: started
      enabled: yes


