
---

  - name: Installing java11 openjdk
    zypper: name=java-11-openjdk state=present

  - name: Installing simple insserv
    zypper: name=insserv-compat state=present

  - name: Checking file elastic rpm
    stat:
      path: /var/tmp/{{ elastic_rpm }}
    register: result

  - name: Downloading elastic rpm file
    get_url:
      url: "{{ elastic_repo }}/{{ elastic_rpm }}"
      dest: /var/tmp/
      mode: 0440
    when: result.stat.exists == False

  - name: Installing the elastic rpm file
    zypper:
      name: /var/tmp/{{ elastic_rpm }}
      disable_gpg_check: yes
      state: present


