
---

  - import_tasks: download-packages.yml

  - name: Installing Elasticsearch on SuSE
    block:
      - include_tasks: ./suse/install-elastic.yml
      - include_tasks: ./suse/install-kibana.yml
      - include_tasks: ./suse/configure-firewall.yml
    when: ansible_os_family|lower == 'suse'

  - name: Installing Elasticsearch on RedHat
    block:
      - include_tasks: ./redhat/install-elastic.yml
      - include_tasks: ./redhat/install-kibana.yml
      - include_tasks: ./redhat/configure-firewall.yml
    when: ansible_os_family|lower == 'redhat'

  - import_tasks: configure-elastic.yml
  - import_tasks: configure-kibana.yml


