
---

  - name: Installing requirements
    yum:
      name: "java-1.8.0-openjdk"
      state: present

  - name: Installing the Elasticsearch RPM
    yum:
      name: /var/tmp/{{ rpm_elastic }}
      disable_gpg_check: yes
      state: present

