
---

  - name: Enabling SuSE firewall
    systemd:
      name: SuSEfirewall2
      enabled: yes
      state: started

  - name: Opening Firewall ports
    lineinfile:
      dest: "{{ susefw_config }}"
      regexp: "^#?FW_SERVICES_ACCEPT_EXT"
      line: "FW_SERVICES_ACCEPT_EXT=\"{{ network }},tcp,5601 {{ network }},tcp,9200\""

  - name: Restarting SuSE firewall
    systemd:
      name: SuSEfirewall2
      state: restarted


