
---

  - name: Installing Java11 openJDK
    zypper: name=java-11-openjdk state=present

  - name: Installing Simple insserv
    zypper: name=insserv-compat state=present

  - name: Installing the Elasticsearch RPM
    zypper:
      name: /var/tmp/{{ elastic_rpm }}
      disable_gpg_check: yes
      state: present

