
---

  - name: Installing requirements
    zypper:
      name: "{{ item }}"
      state: present
    with_items:
      - insserv-compat
      - java-11-openjdk

  - name: Installing the Elasticsearch RPM
    zypper:
      name: /var/tmp/{{ rpm_elastic }}
      disable_gpg_check: yes
      state: present

